components/Header.tsx

This PR adds the link to the nav image.

feat: link the image in the header

---

components/Button.tsx

fix: Missing secondary button

---

components/DropdownMenu.tsx
components/Header.tsx
tailwind.config.js

fix: #31 invisible hamburger menu in smaller screen

---

components/DosDonts.tsx
components/PermittedLogos.tsx
lib/sanity.ts
pages/press/index.tsx
sanity/schemas/openSaucedLogo.js
sanity/schemas/press.js
sanity/schemas/schema.js
tailwind.config.js
types/schema.ts

This PR is related to issue #33.
In this PR a link to press is been created, where there will be OpenSauced logos for third-party usage.
We will be able to add, delete, and edit the press page's content through the sanity admin panel.
Link to access the page:  https://opensauced.pizza/press
Deploy preview link: https://deploy-preview-41--opensauced-landing.netlify.app/press
fixes issue #33

feat: Press to link

---

pages/blog/[slug]/index.tsx

This PR implements sharing button to share OpenSacued blogs on LinkedIn and Hacker news with one click.
Links only link to Twitter #44

feat: Link to share post on LinkedIn and HackerNews

---

lib/sanity.ts
pages/blog/[slug]/index.tsx
pages/blog/index.tsx
sanity/schemas/blog.js
sanity/schemas/feature.js

As mentioned in #54 all the unpublished draft posts were still visible on the front-end. This PR will fix the issue.
Fixes #54

Unpublished draft posts are no longer visible on front-end #54

---

pages/blog/[slug]/index.tsx

Set a fallback to fix the static page generation problem.
More context : https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-true
Fixes #58

Added fallback

---

components/Footer.tsx
pages/blog/[slug]/index.tsx
pages/blog/index.tsx

Fixed issue:
1. Footer was not showing on the "feature" and "blog" pages #52
Also fixed,
3. Footer had a little responsiveness issue on a small screen.
4. Footer context was populating using the index of the array instead of the loop.
#52 
Before
e
After

fixed footer issues

---

components/Header.tsx

All the links in the navbar were behaving like external links.  In this PR 'target=" brank"' has been removed to resolve this problem.
Fixes #53

removed target=blank

---

pages/blog/[slug]/index.tsx
styles/globals.css

As mentioned in #60, there was no style for the link (a tag) in the blog body, this PR fixes that.
Also removed all the anti-pattern tailwind code on the press page and added some modifications to the design.
Preview link: https://deploy-preview-63--opensauced-landing.netlify.app/blog/measuring-success-in-open-source
Fixes #60

Replaced raw css units with tailwind classes and added style to link #60

---

pages/blog/[slug]/index.tsx
sanity/schemas/navigation.js

This PR only modifies the sanity studio. We had to change the type of the URL in the navigation into a plain string to use the local URL. The changes in this PR are already live on the hosted sanity studio.

Modified the URL validation in order to be able to use local URL as well.

---

pages/blog/[slug]/index.tsx
styles/globals.css

Added styles for the Heading elements(H1, H2, H3, etc) in blog posts in order to make them stand out in the blog content.
fixes #65

Styles for the heading elements in blog posts.

---

components/Footer2.tsx
pages/index.tsx

This PR adds a new link to OpenSauced's Tiktok on Footer.

Add OpenSauced's TikTok link

---

components/sections/Subscribe.tsx
components/sections/about/Links.tsx
components/sections/about/about/About.tsx
components/sections/about/about/MetricCard.tsx
components/sections/home-page/GitHubMock.tsx
components/sections/home-page/blogs/Blogs.tsx
components/sections/pricing/features/FeatureCard.tsx
components/sections/pricing/features/Features.tsx
components/sections/pricing/pricing/Pricing.tsx

Went through and added copy for all lorem ipsum. 
The features will need some quick design assistance.

feat: Bdougie copy additions

---

components/sections/about/about/About.tsx
components/sections/pricing/pricing/Pricing.tsx

some copy fixes

---

components/sections/home-page/GitHubMock.tsx

Switching to Orange "however" for legibility reasons.

feat: however to orange

---

styles/blog_text_content_wrapper.css

This PR adds CSS for enabling white space in blogs.
Fixes #99

add css for white space

---

components/sections/blog/[slug]/PageContent.tsx
components/sections/blog/components/Post.tsx
utils/getReadTime.ts

This PR adds functionality to calculate the read time of the blog automatically based on the words count.
Fixes #96

Automate read time

---

components/common/SocialLinks.tsx
components/sections/about/FollowUs.tsx
components/sections/about/Links.tsx
components/sections/about/about/About.tsx
components/sections/about/about/MetricCard.tsx
lib/sanity.ts
pages/about/index.tsx
sanity/deskStructure.js
sanity/sanity.json
sanity/schemas/pages/aboutPage.js
sanity/schemas/schema.js
types/schema.ts

1. [About Page](https://github.com/open-sauced/landing-page/blob/sanity-about/pages/about/index.tsx) with 'Sanity'.
---
This PR will connect the [About Page](https://github.com/open-sauced/landing-page/blob/sanity-about/pages/about/index.tsx)  with the schema [aboutPage.js](https://github.com/open-sauced/landing-page/blob/sanity-about/sanity/schemas/pages/aboutPage.js) of Sanity.
Schema path:  `sanity/schemas/pages/aboutPage.js`
The schema [aboutPage.js](https://github.com/open-sauced/landing-page/blob/sanity-about/sanity/schemas/pages/aboutPage.js) contains everyting needs for the [About Page](https://github.com/open-sauced/landing-page/blob/sanity-about/pages/about/index.tsx)
#103

feat: connection implementation between About Page and Sanity

---

components/sections/home-page/CTA.tsx
components/sections/home-page/GitHubMock.tsx
components/sections/home-page/Hero.tsx
components/sections/home-page/Insights.tsx
components/sections/home-page/Logos.tsx
components/sections/home-page/blogs/Blogs.tsx
components/sections/home-page/features/Feature.tsx
components/sections/home-page/features/Features.tsx
components/sections/home-page/testimonials/Testimonials.tsx
lib/sanity.ts
pages/index.tsx
sanity/deskStructure.js
sanity/schemas/pages/homePage.js
sanity/schemas/schema.js
types/schema.ts

This PR implements connection [Home Page](https://github.com/open-sauced/landing-page/blob/sanity-home/pages/index.tsx) with 'Sanity'.
---
This PR will connect the [Home Page](https://github.com/open-sauced/landing-page/blob/main/pages/index.tsx) with the schema [homePage.js](https://github.com/open-sauced/landing-page/blob/sanity-home/sanity/schemas/pages/homePage.js) of Sanity.
Schema path:  `sanity/schemas/pages/homePage.js`
The schema [homePage.js](https://github.com/open-sauced/landing-page/blob/sanity-home/sanity/schemas/pages/homePage.js) inherits some existing schemas( [user.js](https://github.com/open-sauced/landing-page/blob/sanity-home/sanity/schemas/user.js), [testimonial.js](https://github.com/open-sauced/landing-page/blob/sanity-home/sanity/schemas/testimonial.js) ) on it, …

feat: connection implementation between Home Page and Sanity

---

components/common/SocialShare.tsx
components/sections/blog/[slug]/PageContent.tsx

I created a reuseable component [SocialShare.tsx](https://github.com/open-sauced/landing-page/blob/social-button/components/common/SocialShare.tsx) which currently comes up with 3 types of social sharing (Twitter, Linkedin, Facebook)
1. url <string>: required ( The URL of the site )
2. size <string>: optional ( It can takes `xl` || `lg` || `md` || `sm` || `xs` as an parameter )
3. gap <number>: optional ( Ex: `2` || `3` || `4` || `5` ...)
4. direction <string>: optional (Ex: `direction="row"` || `direction="col"`)
5. twitter <boolean>: optional ( Ex:  `twitter` || `twitter={true}` || `twitter={false}` )
6. linkedIn <boolean>: optional ( Ex: `linkedin` || `linkedin={true}` || `linkedin={false}` )
7. facebook <boolean>: optional ( Ex: `facebook` || `facebook={true}` ||  `facebook={false}` ) …

feat: add social sharing button

---

components/common/SocialLinks.tsx

This PR removes instagram tracking parameters (igshid = instagram share id)

chore(SocialLinks): remove tracking parameters

---

components/sections/Footer.tsx

#116
https://github.com/open-sauced/landing-page/issues/116
This PR fixes the issue with the email at the bottom of the page not being a mailto link
https://github.com/open-sauced/landing-page/issues/116
https://user-images.githubusercontent.com/91942072/227423926-ce40dc63-1ed0-4e99-97b9-4404d0289896.mp4

Converted mail at bottom to mailto #116

---

components/sections/blog/Blogs.tsx
components/sections/home-page/Hero.tsx
components/sections/teams/CTA.tsx
components/sections/teams/GitHubMock.tsx
components/sections/teams/Insights.tsx
components/sections/teams/TeamsHero.tsx
components/sections/teams/TeamsLogos.tsx
components/sections/teams/features/TeamsFeature.tsx
components/sections/teams/features/TeamsFeatures.tsx
pages/teams/index.tsx

This PR adds the previous landing to the route '/teams'.
#121

feat: Team's landing page

---

components/common/Button.tsx
components/common/ContainerWithLine.tsx
components/common/GradientBorderWrapper.tsx
components/common/layout/PageLayout.tsx
components/common/layout/SectionWrapper.tsx
components/common/text/Heading.tsx
components/common/text/Typography.tsx
components/hooks/useMediaQuery.ts
components/sections/Footer.tsx
components/sections/about/Background.tsx
components/sections/blog/Background.tsx
components/sections/blog/[slug]/PageContent.tsx
components/sections/blog/components/LocalTypography.tsx
components/sections/home-page/Background.tsx
components/sections/home-page/blogs/Blog.tsx
components/sections/home-page/testimonials/Testimonial.tsx
components/sections/press/PressBackground.tsx
components/sections/pricing/Background.tsx
package-lock.json
package.json
pages/u/[username]/index.tsx

This PR adds the feature to redirect OpenSauced users to the Insight app.
E.g: `opensauced.pizza/u/bdougie` to `https://insights.opensauced.pizza/user/bdougie`
**Suddenly there was an error coming up with an older version of `@react/types`. So, I had to update it to version 18 and do some code refactoring for type checking.**

feat: Add user redirect & Update @react/types

---

lib/sanity.ts
pages/blog/index.tsx

1. Attempted to fetch "featuredBlogs" from the backend, but it does not exist in the database. Refactored the code to cease the attempt of fetching it (It was also being fetched in some other parts of the code, requiring an inspection to remove those instances as well).
2. Initially, all blogs were fetched unsorted from the backend, resulting in potential blog omissions when sorting was done on the frontend. This sorting operation shouldn't be performed on the frontend. Refactored the code to fetch sorted data directly from the backend.
This fixes #132

feat: Resolve blog fetching

---

styles/blog_text_content_wrapper.css

Fixes #136
Added styles to differentiate internal and external links. Applied a highlight color and underline effect.

fix: Add highlighting for links in the blog page

---

components/common/SocialLinks.tsx
components/sections/Footer.tsx
components/sections/Subscribe.tsx
pages/_document.tsx
sanity/package-lock.json
sanity/yarn.lock

This PR includes various updates and fixes. It fixes the issue of sauced items overflowing on small devices. It also updates dependencies such as minimist, ua-parser-js, word-wrap, semver, and decode-uri-component to their latest versions. Additionally, it addresses the mismatched selection color and includes style details.
_Generated using [OpenSauced](https://opensauced.ai/)._
Fixes #139

fix: fixed more sauced items overflow on small devices

---

components/sections/home-page/testimonials/Testimonials.tsx

fixed the text overflow on testimonial section
Fixes #147

Fix: fixed text overflow on testimonial

---

components/sections/home-page/testimonials/Testimonial.tsx

This PR fixes the issue where the animation is overflowing, causing the top and bottom of the card to get cut in-between animations. Additionally, it addresses the problem of the orange box shadow being cut when the animation is complete.
#156

fix: fixed irregular animation card border display

---

next.config.js

- Adds `X-Frame-Options` headers to prevent the landing page from being loaded inside an iframe
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
Tests: 
Before:
https://iframetester.com/?url=https://opensauced.pizza
After:
https://iframetester.com/?url=https://deploy-preview-159--opensauced-landing.netlify.app/

fix: add headers to prevent site being embedded in an iframe

---

components/common/layout/PageLayout.tsx
components/common/layout/SEO/SEO.tsx
components/sections/blog/[slug]/PageContent.tsx
pages/_document.tsx

converted the OgData file into SEO layout and added description it 
Fixes #49

feat: changed OgData to SEO layout

---

components/sections/changelog/Background.tsx
components/sections/changelog/Changelog.tsx
components/sections/changelog/Changelogs.tsx
components/sections/changelog/Hero.tsx
components/sections/navigation/Header.tsx
lib/sanity.ts
package-lock.json
package.json
pages/changelog/index.tsx
sanity/schemas/changelog.js
sanity/schemas/changelogCategory.js
sanity/schemas/schema.js
sanity/yarn.lock
tailwind.config.js
types/schema.ts

The Changelog page is live on: https://deploy-preview-190--opensauced-landing.netlify.app/changelog
1. Initially 5 changelogs will be displayed, user has to press the `load more button` to see another 5 more changelog posts.
2. Changelogs are sorted descendingly based on the date field.
3. The changelog will be displayed initially in 120-pixel heights, to see the full content users have to click on the `see more` button.
4. The logic behind the `see more` is it will only appear if the changelog content has any image(because no image will be shown properly in 120 pixels height) or the it has more than 260 characters.
Also, this PR checks all the checkboxes in the comment below.
https://github.com/open-sauced/landing-page/pull/190#issuecomment-1916873057

feat: Add new changelog page/

---

components/sections/changelog/Hero.tsx

fix: Update Hero.tsx

---

middleware.ts
next.config.js
package-lock.json
package.json
pages/contributors/index.tsx

Relates to #208
Relates to #209
1. Go to `/` in the deploy preview
2. You're redirected to `/teams`

fix: fixed teams redirect

---

components/sections/home-page/Hero.tsx
components/sections/home-page/features/TeamsFeatures.tsx

Shows the hero image set in the Sanity CMS. Also lands a fix to the top use case layouts in mobile view.
BEFORE
AFTER

fix: show sanity hero image

---

package-lock.json
package.json

Starting off my first day back with some reverts. 😅 
Relates to #212
Same test steps as #212

fix: reverted some package.json changes that were old dependencies

---

components/sections/changelog/Hero.tsx
components/sections/navigation/DesktopNavigation.tsx
components/sections/navigation/Header.tsx
components/sections/navigation/MobileNavigation.tsx

Adds a drop down menu that leads to various use cases pages
Closes #207

feat: add use cases menu

---

middleware.ts

Although `/` redirecting to `/teams` works, we wanted to have a rewrite instead.
Relates to #206
1. Go to `/`
2. It loads as the homepage which is the same contents as `/teams`.

fix: now / rewrites, not redirects to /teams

---

components/sections/navigation/DropdownMenu.tsx

Removed `Transition` component from headlessui that blocked showing the navigation menu on mobile views.
https://github.com/open-sauced/landing-page/assets/20603494/7ce9809b-6dfc-49ed-b6ca-ee2038684ed5

fix: show mobile nav menu

---

components/sections/navigation/DesktopNavigation.tsx

Had an instance where I got to watch someone try to log into our app from the landing page and many questions came up. It is not clear what "connecting with github" means in the context of our landing page. I am swapping the with to your in this PR.
before:
after:

feat: connect your github sounds better

---

components/common/SocialLinks.tsx
components/common/StarTheRepo.tsx
components/sections/Footer.tsx
components/sections/about/Links.tsx
components/sections/blog/[slug]/PageContent.tsx
components/sections/home-page/Logos.tsx
components/sections/maintainers/Logos.tsx
components/sections/teams/TeamsLogos.tsx

- Removes occurrences of rel="noreferrer" for improved SEO performance
Closes https://github.com/open-sauced/landing-page/issues/239

fix: remove occurrences of rel="noreferrer" for SEO improvements

---

pages/api/rss/changelog.ts

fix: changelog.ts to changelog slug

---

public/robots.txt

This file should be here for SEO purposes. We can add restrictions when needed.

feat: Create robots.txt

---

components/sections/Footer.tsx
components/sections/navigation/DesktopNavigation.tsx
pages/u/[username]/index.tsx
sanity/schemas/pages/aboutPage.js
types/schema.ts

We were still using the old link for app in a couple of places.
closes #245 
Go to opensauced.pizza. Look at the footer for app.opensauced.pizza.

fix: Replace insights.opensauced with app.opensauced

---

components/sections/blog/[slug]/PageContent.tsx
components/sections/blog/components/Post.tsx
sanity/schemas/blog.js
types/schema.ts

Implements a "published date" field to the Sanity CMS and displays it as part of a blog's info.
Closes #237 
Blog page header
Featured blog
Recent posts

feat: add "published date" to blog schema

---

components/sections/blog/Blogs.tsx
components/sections/blog/FeaturedPost.tsx
components/sections/blog/[slug]/PageContent.tsx
components/sections/blog/components/AuthorBio.tsx
components/sections/blog/components/Post.tsx
lib/sanity.ts
pages/api/rss/blog.ts
pages/blog/[slug]/index.tsx
pages/blog/index.tsx
sanity/schemas/author.js
sanity/schemas/blog.js
sanity/schemas/schema.js
types/schema.ts

Implements an `Author` schema to Sanity and displays their bios in the blog post page.
Closes #238

feat: add author bios to blogs

---

components/sections/navigation/DropdownMenu.tsx

I think I messed this up when I was triaging for #260
fixes #265
1. Open mobile view
2. open hamburger menu

fix hamburger z-index

---

components/sections/blog/[slug]/PageContent.tsx

It's the same problem I fixed here: https://github.com/open-sauced/landing-page/pull/262.
For some reason added a hardcoded height and it sucks.
before
after

fix: Remove height from images

---

components/sections/home-page/features/TeamsFeatures.tsx
lib/sanity.ts
pages/contributors/index.tsx
sanity/deskStructure.js
sanity/schemas/pages/contributorsPage.js
sanity/schemas/schema.js
types/schema.ts

Updates the copy for `/contributors` with a new page in the Sanity CMS.

feat: update `/contributors` copy

---

lib/sanity.ts
pages/maintainers/index.tsx
sanity/deskStructure.js
sanity/schemas/pages/maintainersPage.js
sanity/schemas/schema.js
types/schema.ts

Updates the copy for `/maintainers` with a new page in the Sanity CMS.
Closes #234

feat: update `/maintainers` copy

---

components/sections/press/PressHeading.tsx
pages/404.tsx

created a new branch from codespaces by accident. 
This removes more z-50 usage.

remove z-50 from pages

---

components/common/product-hunt/PHBadge.tsx
components/common/product-hunt/PHBadgeDark.tsx

fix: Update PHBadge.tsx

---

components/sections/lunchweek/Launches.tsx

Add day four to lunch week
- go to /lunchweek
- See StarSearch

Add StarSearch to day 4

---

components/common/product-hunt/PHBadge.tsx
components/common/product-hunt/PHBadgeDark.tsx

Updates to latest PG badges
closes #297 
1. go to homepage, see badge on the bottom right

fix: Update PH Badges

---

lib/sanity.ts
next.config.js
pages/sitemap.xml.tsx
public/robots.txt

closes #264 
- got to opensauced.pizza/sitemap.xml

feat: add sitemap

---

next.config.js

We're working on improving the SEO of our site. A quick win is to have our docs become a subdirectory instead of a subdomain. This sets it up.
closes #300 
Works using deploy preview for docs PR:
https://github.com/open-sauced/landing-page/assets/34313413/e49c8e6a-ca57-4d5f-b899-da48cf642fe9
1. Run this project locally
2. Change the destination in the next.config.js to this: 
{
source: '/docs/:path*',
destination: 'https://deploy-preview-309--docs-open.netlify.app/:path*',
},
{
source: '/docs/',
destination: 'https://deploy-preview-309--docs-open.netlify.app/',
}
3. go to http://localhost:3000/docs.

feat: set up for docs to be a subdirectory

---

next.config.js

Fix: fix redirects

---

netlify.toml
next.config.js
public/_redirects

We need to create a subdirectory for our open source courses on our site. This sets it up to do that.
closes #308
1. To check this locally, you'll need to change the next.config.js line 32 to  `destination: 'https://deploy-preview-227--sauced-intro.netlify.app/:path*/',`
2. run locally and navigate to opensauced.pizza/learn

feat: add redirect for intro course

---

next.config.js

The redirects weren't working, so we needed to create a new empty site to fix the redirects from intro.opensauced.pizza -> opensauced.pizza/learn

fix: new site link for courses to fix redirects

---

public/robots.txt

We added the subdirectories for docs and learn, but didn't add the sitemaps to robots.txt. This fixes that. 
closes #318

fix: Add docs and learn sitemaps for SEO

---

package-lock.json
package.json

Related to Dependabot alerts and updates: Upgrades to Next 14
Succeeds bot commits - Closes: https://github.com/open-sauced/landing-page/pull/269
Validated locally, looks good 👍🏼

feat: Upgrade to Next 14

---

components/sections/blog/[slug]/BlogTextContent.tsx

Implements TailwindCSS' typography plugin by adding `prose prose-invert` to `<BlogTextContent />` that renders the different HTML tags correctly, including `blockquote`.
Closes #338 
**Left: PR changes | Right: Prod**
1. Go to `/blog` and pick a post
2. Ensure any quotes are rendered correctly (italics with a left bar)

feat: update Quote rendering for blog posts

---

components/sections/changelog/Changelog.tsx

This pull request fixes the changelog Entries that aren't clickable on mobile
Fixes #344

fix: fixed changelog Entries that aren't clickable on mobile

---

.github/CODEOWNERS
.github/workflows/pizza.yml
.sauced.yaml

adds the [pizza-action](https://github.com/open-sauced/pizza-action) GitHub action to the project, removes the old CODEOWNERS file in favour of the root one that will get generated by the pizza-action, and adds a .sauced.yaml file for attributions that will generate/update CODEOWNERS among other things in the future.
This will allow us to update the CODEOWNERS file on a weekly cadence on Sunday night's at midnight UTC.
Closes #351
N/A
This can only be tested once merged, but we've already enabled it on the open-sauced/app repository, and the repository settings already allow GitHub actions to create pull requests, so this should be all set to go.

chore: added pizza-action to the project

---

components/sections/blog/[slug]/PageContent.tsx

fix the clock alignment in the blogs page
Fixes #348 
before:
after:

aligned the clock icon in block to center

---

components/sections/changelog/Changelog.tsx
pages/changelog/[slug].tsx

This pull request fixes the changelog subtext color
Fixes #198 
before:
after:

fix: changelog subtext has accessible colour contrast now

---

.github/workflows/pizza.yml

Updates the pizza-action to v2.2..0 and it now uses v2.1.0 version of the pizza CLI.
Closes #364

chore: updated pizza action

---

.github/workflows/pizza.yml

chore: update pizza action version

---

.sauced.yaml
CODEOWNERS

This didn't have my user id or secondary email, so I wasn't being added to the codeowners file. This makes those corrections and updates codeowners to be more accurate.
closes #378

fix: update sauced.yaml with correct emails for Bekah

---

components/sections/Footer.tsx
components/sections/home-page/CTA.tsx
components/sections/home-page/Hero.tsx
components/sections/maintainers/CTA.tsx
components/sections/maintainers/Hero.tsx
components/sections/navigation/DesktopNavigation.tsx
components/sections/teams/CTA.tsx

Fixes #413
Remove all links to `app.opensauced.pizza` from the codebase.
* Remove the `Button` component for "Connect your GitHub" in `components/sections/navigation/DesktopNavigation.tsx`.
* Remove the `Button` components in `components/sections/home-page/Hero.tsx`.
* Remove the `Button` components in `components/sections/maintainers/Hero.tsx`.
* Remove the `Button` component in `components/sections/home-page/CTA.tsx`.
* Remove the `Button` component in `components/sections/maintainers/CTA.tsx`.
* Remove the `Button` component in `components/sections/teams/CTA.tsx`.
* Remove the link to `app.opensauced.pizza` from the `apps` array in `components/sections/Footer.tsx`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/open-sauced/landing-pag …

Remove login

---

components/sections/Footer.tsx
components/sections/home-page/Newsletter.tsx

Related to #417
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/open-sauced/landing-page/pull/418?shareId=9a1c324e-7fbe-44eb-beec-5af8d7240c60).

Update newsletter links to new service
